/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicantCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicantCreate{}

// ApplicantCreate struct for ApplicantCreate
type ApplicantCreate struct {
	// The applicant's first name
	FirstName string `json:"first_name" validate:"regexp=^[^!#$%*=<>;{}\\"]*$"`
	// The applicant's surname
	LastName string `json:"last_name" validate:"regexp=^[^!#$%*=<>;{}\\"]*$"`
}

type _ApplicantCreate ApplicantCreate

// NewApplicantCreate instantiates a new ApplicantCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicantCreate(firstName string, lastName string) *ApplicantCreate {
	this := ApplicantCreate{}
	this.FirstName = firstName
	this.LastName = lastName
	return &this
}

// NewApplicantCreateWithDefaults instantiates a new ApplicantCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicantCreateWithDefaults() *ApplicantCreate {
	this := ApplicantCreate{}
	return &this
}

// GetFirstName returns the FirstName field value
func (o *ApplicantCreate) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ApplicantCreate) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ApplicantCreate) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *ApplicantCreate) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *ApplicantCreate) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *ApplicantCreate) SetLastName(v string) {
	o.LastName = v
}

func (o ApplicantCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicantCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	return toSerialize, nil
}

func (o *ApplicantCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_name",
		"last_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicantCreate := _ApplicantCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicantCreate)

	if err != nil {
		return err
	}

	*o = ApplicantCreate(varApplicantCreate)

	return err
}

type NullableApplicantCreate struct {
	value *ApplicantCreate
	isSet bool
}

func (v NullableApplicantCreate) Get() *ApplicantCreate {
	return v.value
}

func (v *NullableApplicantCreate) Set(val *ApplicantCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicantCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicantCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicantCreate(val *ApplicantCreate) *NullableApplicantCreate {
	return &NullableApplicantCreate{value: val, isSet: true}
}

func (v NullableApplicantCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicantCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


