/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityMotionBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityMotionBreakdown{}

// FacialSimilarityMotionBreakdown struct for FacialSimilarityMotionBreakdown
type FacialSimilarityMotionBreakdown struct {
	FaceComparison *FacialSimilarityMotionBreakdownFaceComparison `json:"face_comparison,omitempty"`
	ImageIntegrity *FacialSimilarityMotionBreakdownImageIntegrity `json:"image_integrity,omitempty"`
	VisualAuthenticity *FacialSimilarityMotionBreakdownVisualAuthenticity `json:"visual_authenticity,omitempty"`
}

// NewFacialSimilarityMotionBreakdown instantiates a new FacialSimilarityMotionBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityMotionBreakdown() *FacialSimilarityMotionBreakdown {
	this := FacialSimilarityMotionBreakdown{}
	return &this
}

// NewFacialSimilarityMotionBreakdownWithDefaults instantiates a new FacialSimilarityMotionBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityMotionBreakdownWithDefaults() *FacialSimilarityMotionBreakdown {
	this := FacialSimilarityMotionBreakdown{}
	return &this
}

// GetFaceComparison returns the FaceComparison field value if set, zero value otherwise.
func (o *FacialSimilarityMotionBreakdown) GetFaceComparison() FacialSimilarityMotionBreakdownFaceComparison {
	if o == nil || IsNil(o.FaceComparison) {
		var ret FacialSimilarityMotionBreakdownFaceComparison
		return ret
	}
	return *o.FaceComparison
}

// GetFaceComparisonOk returns a tuple with the FaceComparison field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityMotionBreakdown) GetFaceComparisonOk() (*FacialSimilarityMotionBreakdownFaceComparison, bool) {
	if o == nil || IsNil(o.FaceComparison) {
		return nil, false
	}
	return o.FaceComparison, true
}

// HasFaceComparison returns a boolean if a field has been set.
func (o *FacialSimilarityMotionBreakdown) HasFaceComparison() bool {
	if o != nil && !IsNil(o.FaceComparison) {
		return true
	}

	return false
}

// SetFaceComparison gets a reference to the given FacialSimilarityMotionBreakdownFaceComparison and assigns it to the FaceComparison field.
func (o *FacialSimilarityMotionBreakdown) SetFaceComparison(v FacialSimilarityMotionBreakdownFaceComparison) {
	o.FaceComparison = &v
}

// GetImageIntegrity returns the ImageIntegrity field value if set, zero value otherwise.
func (o *FacialSimilarityMotionBreakdown) GetImageIntegrity() FacialSimilarityMotionBreakdownImageIntegrity {
	if o == nil || IsNil(o.ImageIntegrity) {
		var ret FacialSimilarityMotionBreakdownImageIntegrity
		return ret
	}
	return *o.ImageIntegrity
}

// GetImageIntegrityOk returns a tuple with the ImageIntegrity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityMotionBreakdown) GetImageIntegrityOk() (*FacialSimilarityMotionBreakdownImageIntegrity, bool) {
	if o == nil || IsNil(o.ImageIntegrity) {
		return nil, false
	}
	return o.ImageIntegrity, true
}

// HasImageIntegrity returns a boolean if a field has been set.
func (o *FacialSimilarityMotionBreakdown) HasImageIntegrity() bool {
	if o != nil && !IsNil(o.ImageIntegrity) {
		return true
	}

	return false
}

// SetImageIntegrity gets a reference to the given FacialSimilarityMotionBreakdownImageIntegrity and assigns it to the ImageIntegrity field.
func (o *FacialSimilarityMotionBreakdown) SetImageIntegrity(v FacialSimilarityMotionBreakdownImageIntegrity) {
	o.ImageIntegrity = &v
}

// GetVisualAuthenticity returns the VisualAuthenticity field value if set, zero value otherwise.
func (o *FacialSimilarityMotionBreakdown) GetVisualAuthenticity() FacialSimilarityMotionBreakdownVisualAuthenticity {
	if o == nil || IsNil(o.VisualAuthenticity) {
		var ret FacialSimilarityMotionBreakdownVisualAuthenticity
		return ret
	}
	return *o.VisualAuthenticity
}

// GetVisualAuthenticityOk returns a tuple with the VisualAuthenticity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityMotionBreakdown) GetVisualAuthenticityOk() (*FacialSimilarityMotionBreakdownVisualAuthenticity, bool) {
	if o == nil || IsNil(o.VisualAuthenticity) {
		return nil, false
	}
	return o.VisualAuthenticity, true
}

// HasVisualAuthenticity returns a boolean if a field has been set.
func (o *FacialSimilarityMotionBreakdown) HasVisualAuthenticity() bool {
	if o != nil && !IsNil(o.VisualAuthenticity) {
		return true
	}

	return false
}

// SetVisualAuthenticity gets a reference to the given FacialSimilarityMotionBreakdownVisualAuthenticity and assigns it to the VisualAuthenticity field.
func (o *FacialSimilarityMotionBreakdown) SetVisualAuthenticity(v FacialSimilarityMotionBreakdownVisualAuthenticity) {
	o.VisualAuthenticity = &v
}

func (o FacialSimilarityMotionBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityMotionBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FaceComparison) {
		toSerialize["face_comparison"] = o.FaceComparison
	}
	if !IsNil(o.ImageIntegrity) {
		toSerialize["image_integrity"] = o.ImageIntegrity
	}
	if !IsNil(o.VisualAuthenticity) {
		toSerialize["visual_authenticity"] = o.VisualAuthenticity
	}
	return toSerialize, nil
}

type NullableFacialSimilarityMotionBreakdown struct {
	value *FacialSimilarityMotionBreakdown
	isSet bool
}

func (v NullableFacialSimilarityMotionBreakdown) Get() *FacialSimilarityMotionBreakdown {
	return v.value
}

func (v *NullableFacialSimilarityMotionBreakdown) Set(val *FacialSimilarityMotionBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityMotionBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityMotionBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityMotionBreakdown(val *FacialSimilarityMotionBreakdown) *NullableFacialSimilarityMotionBreakdown {
	return &NullableFacialSimilarityMotionBreakdown{value: val, isSet: true}
}

func (v NullableFacialSimilarityMotionBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityMotionBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


