/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WebhookUpdater type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookUpdater{}

// WebhookUpdater struct for WebhookUpdater
type WebhookUpdater struct {
	// Determine if the webhook is active.
	Enabled *bool `json:"enabled,omitempty"`
	// The events that will be published to the webhook. If the events parameter is omitted all the events will be subscribed. 
	Events []WebhookEventType `json:"events,omitempty"`
	// The environments from which the webhook will receive events. Allowed values are “sandbox” and “live”. If the environments parameter is omitted the webhook will receive events from both environments. 
	Environments []string `json:"environments,omitempty"`
	// Webhook version used to control the payload object when sending webhooks.
	PayloadVersion *int32 `json:"payload_version,omitempty"`
	// The url that will listen to notifications (must be https).
	Url *string `json:"url,omitempty"`
}

// NewWebhookUpdater instantiates a new WebhookUpdater object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookUpdater() *WebhookUpdater {
	this := WebhookUpdater{}
	return &this
}

// NewWebhookUpdaterWithDefaults instantiates a new WebhookUpdater object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookUpdaterWithDefaults() *WebhookUpdater {
	this := WebhookUpdater{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *WebhookUpdater) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdater) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *WebhookUpdater) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *WebhookUpdater) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *WebhookUpdater) GetEvents() []WebhookEventType {
	if o == nil || IsNil(o.Events) {
		var ret []WebhookEventType
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdater) GetEventsOk() ([]WebhookEventType, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookUpdater) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []WebhookEventType and assigns it to the Events field.
func (o *WebhookUpdater) SetEvents(v []WebhookEventType) {
	o.Events = v
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *WebhookUpdater) GetEnvironments() []string {
	if o == nil || IsNil(o.Environments) {
		var ret []string
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdater) GetEnvironmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *WebhookUpdater) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []string and assigns it to the Environments field.
func (o *WebhookUpdater) SetEnvironments(v []string) {
	o.Environments = v
}

// GetPayloadVersion returns the PayloadVersion field value if set, zero value otherwise.
func (o *WebhookUpdater) GetPayloadVersion() int32 {
	if o == nil || IsNil(o.PayloadVersion) {
		var ret int32
		return ret
	}
	return *o.PayloadVersion
}

// GetPayloadVersionOk returns a tuple with the PayloadVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdater) GetPayloadVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.PayloadVersion) {
		return nil, false
	}
	return o.PayloadVersion, true
}

// HasPayloadVersion returns a boolean if a field has been set.
func (o *WebhookUpdater) HasPayloadVersion() bool {
	if o != nil && !IsNil(o.PayloadVersion) {
		return true
	}

	return false
}

// SetPayloadVersion gets a reference to the given int32 and assigns it to the PayloadVersion field.
func (o *WebhookUpdater) SetPayloadVersion(v int32) {
	o.PayloadVersion = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhookUpdater) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdater) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhookUpdater) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhookUpdater) SetUrl(v string) {
	o.Url = &v
}

func (o WebhookUpdater) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookUpdater) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	if !IsNil(o.PayloadVersion) {
		toSerialize["payload_version"] = o.PayloadVersion
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableWebhookUpdater struct {
	value *WebhookUpdater
	isSet bool
}

func (v NullableWebhookUpdater) Get() *WebhookUpdater {
	return v.value
}

func (v *NullableWebhookUpdater) Set(val *WebhookUpdater) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookUpdater) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookUpdater) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookUpdater(val *WebhookUpdater) *NullableWebhookUpdater {
	return &NullableWebhookUpdater{value: val, isSet: true}
}

func (v NullableWebhookUpdater) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookUpdater) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


