/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity{}

// FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity Asserts whether the quality and integrity of the uploaded files were sufficient to perform a face comparison.
type FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity struct {
	Result *string `json:"result,omitempty"`
	Breakdown *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown `json:"breakdown,omitempty"`
}

// NewFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity instantiates a new FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity() *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity {
	this := FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity{}
	return &this
}

// NewFacialSimilarityPhotoFullyAutoBreakdownImageIntegrityWithDefaults instantiates a new FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityPhotoFullyAutoBreakdownImageIntegrityWithDefaults() *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity {
	this := FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) GetBreakdown() FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) GetBreakdownOk() (*FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown and assigns it to the Breakdown field.
func (o *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) SetBreakdown(v FacialSimilarityPhotoFullyAutoBreakdownImageIntegrityBreakdown) {
	o.Breakdown = &v
}

func (o FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity struct {
	value *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity
	isSet bool
}

func (v NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) Get() *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity {
	return v.value
}

func (v *NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) Set(val *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity(val *FacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) *NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity {
	return &NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity{value: val, isSet: true}
}

func (v NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityPhotoFullyAutoBreakdownImageIntegrity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


