/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// Report - struct for Report
type Report struct {
	DeviceIntelligenceReport *DeviceIntelligenceReport
	DocumentReport *DocumentReport
	DocumentVideoReport *DocumentVideoReport
	DocumentVideoWithAddressInformationReport *DocumentVideoWithAddressInformationReport
	DocumentWithAddressInformationReport *DocumentWithAddressInformationReport
	DocumentWithDriverVerificationReport *DocumentWithDriverVerificationReport
	DocumentWithDrivingLicenceInformationReport *DocumentWithDrivingLicenceInformationReport
	FacialSimilarityMotionReport *FacialSimilarityMotionReport
	FacialSimilarityPhotoFullyAutoReport *FacialSimilarityPhotoFullyAutoReport
	FacialSimilarityPhotoReport *FacialSimilarityPhotoReport
	FacialSimilarityVideoReport *FacialSimilarityVideoReport
	IdentityEnhancedReport *IdentityEnhancedReport
	IndiaPanReport *IndiaPanReport
	KnownFacesReport *KnownFacesReport
	ProofOfAddressReport *ProofOfAddressReport
	UsDrivingLicenceReport *UsDrivingLicenceReport
	WatchlistAmlReport *WatchlistAmlReport
	WatchlistEnhancedReport *WatchlistEnhancedReport
	WatchlistPepsOnlyReport *WatchlistPepsOnlyReport
	WatchlistSanctionsOnlyReport *WatchlistSanctionsOnlyReport
	WatchlistStandardReport *WatchlistStandardReport
}

// DeviceIntelligenceReportAsReport is a convenience function that returns DeviceIntelligenceReport wrapped in Report
func DeviceIntelligenceReportAsReport(v *DeviceIntelligenceReport) Report {
	return Report{
		DeviceIntelligenceReport: v,
	}
}

// DocumentReportAsReport is a convenience function that returns DocumentReport wrapped in Report
func DocumentReportAsReport(v *DocumentReport) Report {
	return Report{
		DocumentReport: v,
	}
}

// DocumentVideoReportAsReport is a convenience function that returns DocumentVideoReport wrapped in Report
func DocumentVideoReportAsReport(v *DocumentVideoReport) Report {
	return Report{
		DocumentVideoReport: v,
	}
}

// DocumentVideoWithAddressInformationReportAsReport is a convenience function that returns DocumentVideoWithAddressInformationReport wrapped in Report
func DocumentVideoWithAddressInformationReportAsReport(v *DocumentVideoWithAddressInformationReport) Report {
	return Report{
		DocumentVideoWithAddressInformationReport: v,
	}
}

// DocumentWithAddressInformationReportAsReport is a convenience function that returns DocumentWithAddressInformationReport wrapped in Report
func DocumentWithAddressInformationReportAsReport(v *DocumentWithAddressInformationReport) Report {
	return Report{
		DocumentWithAddressInformationReport: v,
	}
}

// DocumentWithDriverVerificationReportAsReport is a convenience function that returns DocumentWithDriverVerificationReport wrapped in Report
func DocumentWithDriverVerificationReportAsReport(v *DocumentWithDriverVerificationReport) Report {
	return Report{
		DocumentWithDriverVerificationReport: v,
	}
}

// DocumentWithDrivingLicenceInformationReportAsReport is a convenience function that returns DocumentWithDrivingLicenceInformationReport wrapped in Report
func DocumentWithDrivingLicenceInformationReportAsReport(v *DocumentWithDrivingLicenceInformationReport) Report {
	return Report{
		DocumentWithDrivingLicenceInformationReport: v,
	}
}

// FacialSimilarityMotionReportAsReport is a convenience function that returns FacialSimilarityMotionReport wrapped in Report
func FacialSimilarityMotionReportAsReport(v *FacialSimilarityMotionReport) Report {
	return Report{
		FacialSimilarityMotionReport: v,
	}
}

// FacialSimilarityPhotoFullyAutoReportAsReport is a convenience function that returns FacialSimilarityPhotoFullyAutoReport wrapped in Report
func FacialSimilarityPhotoFullyAutoReportAsReport(v *FacialSimilarityPhotoFullyAutoReport) Report {
	return Report{
		FacialSimilarityPhotoFullyAutoReport: v,
	}
}

// FacialSimilarityPhotoReportAsReport is a convenience function that returns FacialSimilarityPhotoReport wrapped in Report
func FacialSimilarityPhotoReportAsReport(v *FacialSimilarityPhotoReport) Report {
	return Report{
		FacialSimilarityPhotoReport: v,
	}
}

// FacialSimilarityVideoReportAsReport is a convenience function that returns FacialSimilarityVideoReport wrapped in Report
func FacialSimilarityVideoReportAsReport(v *FacialSimilarityVideoReport) Report {
	return Report{
		FacialSimilarityVideoReport: v,
	}
}

// IdentityEnhancedReportAsReport is a convenience function that returns IdentityEnhancedReport wrapped in Report
func IdentityEnhancedReportAsReport(v *IdentityEnhancedReport) Report {
	return Report{
		IdentityEnhancedReport: v,
	}
}

// IndiaPanReportAsReport is a convenience function that returns IndiaPanReport wrapped in Report
func IndiaPanReportAsReport(v *IndiaPanReport) Report {
	return Report{
		IndiaPanReport: v,
	}
}

// KnownFacesReportAsReport is a convenience function that returns KnownFacesReport wrapped in Report
func KnownFacesReportAsReport(v *KnownFacesReport) Report {
	return Report{
		KnownFacesReport: v,
	}
}

// ProofOfAddressReportAsReport is a convenience function that returns ProofOfAddressReport wrapped in Report
func ProofOfAddressReportAsReport(v *ProofOfAddressReport) Report {
	return Report{
		ProofOfAddressReport: v,
	}
}

// UsDrivingLicenceReportAsReport is a convenience function that returns UsDrivingLicenceReport wrapped in Report
func UsDrivingLicenceReportAsReport(v *UsDrivingLicenceReport) Report {
	return Report{
		UsDrivingLicenceReport: v,
	}
}

// WatchlistAmlReportAsReport is a convenience function that returns WatchlistAmlReport wrapped in Report
func WatchlistAmlReportAsReport(v *WatchlistAmlReport) Report {
	return Report{
		WatchlistAmlReport: v,
	}
}

// WatchlistEnhancedReportAsReport is a convenience function that returns WatchlistEnhancedReport wrapped in Report
func WatchlistEnhancedReportAsReport(v *WatchlistEnhancedReport) Report {
	return Report{
		WatchlistEnhancedReport: v,
	}
}

// WatchlistPepsOnlyReportAsReport is a convenience function that returns WatchlistPepsOnlyReport wrapped in Report
func WatchlistPepsOnlyReportAsReport(v *WatchlistPepsOnlyReport) Report {
	return Report{
		WatchlistPepsOnlyReport: v,
	}
}

// WatchlistSanctionsOnlyReportAsReport is a convenience function that returns WatchlistSanctionsOnlyReport wrapped in Report
func WatchlistSanctionsOnlyReportAsReport(v *WatchlistSanctionsOnlyReport) Report {
	return Report{
		WatchlistSanctionsOnlyReport: v,
	}
}

// WatchlistStandardReportAsReport is a convenience function that returns WatchlistStandardReport wrapped in Report
func WatchlistStandardReportAsReport(v *WatchlistStandardReport) Report {
	return Report{
		WatchlistStandardReport: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Report) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DeviceIntelligenceReport
	err = newStrictDecoder(data).Decode(&dst.DeviceIntelligenceReport)
	if err == nil {
		jsonDeviceIntelligenceReport, _ := json.Marshal(dst.DeviceIntelligenceReport)
		if string(jsonDeviceIntelligenceReport) == "{}" { // empty struct
			dst.DeviceIntelligenceReport = nil
		} else {
			if err = validator.Validate(dst.DeviceIntelligenceReport); err != nil {
				dst.DeviceIntelligenceReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DeviceIntelligenceReport = nil
	}

	// try to unmarshal data into DocumentReport
	err = newStrictDecoder(data).Decode(&dst.DocumentReport)
	if err == nil {
		jsonDocumentReport, _ := json.Marshal(dst.DocumentReport)
		if string(jsonDocumentReport) == "{}" { // empty struct
			dst.DocumentReport = nil
		} else {
			if err = validator.Validate(dst.DocumentReport); err != nil {
				dst.DocumentReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentReport = nil
	}

	// try to unmarshal data into DocumentVideoReport
	err = newStrictDecoder(data).Decode(&dst.DocumentVideoReport)
	if err == nil {
		jsonDocumentVideoReport, _ := json.Marshal(dst.DocumentVideoReport)
		if string(jsonDocumentVideoReport) == "{}" { // empty struct
			dst.DocumentVideoReport = nil
		} else {
			if err = validator.Validate(dst.DocumentVideoReport); err != nil {
				dst.DocumentVideoReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentVideoReport = nil
	}

	// try to unmarshal data into DocumentVideoWithAddressInformationReport
	err = newStrictDecoder(data).Decode(&dst.DocumentVideoWithAddressInformationReport)
	if err == nil {
		jsonDocumentVideoWithAddressInformationReport, _ := json.Marshal(dst.DocumentVideoWithAddressInformationReport)
		if string(jsonDocumentVideoWithAddressInformationReport) == "{}" { // empty struct
			dst.DocumentVideoWithAddressInformationReport = nil
		} else {
			if err = validator.Validate(dst.DocumentVideoWithAddressInformationReport); err != nil {
				dst.DocumentVideoWithAddressInformationReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentVideoWithAddressInformationReport = nil
	}

	// try to unmarshal data into DocumentWithAddressInformationReport
	err = newStrictDecoder(data).Decode(&dst.DocumentWithAddressInformationReport)
	if err == nil {
		jsonDocumentWithAddressInformationReport, _ := json.Marshal(dst.DocumentWithAddressInformationReport)
		if string(jsonDocumentWithAddressInformationReport) == "{}" { // empty struct
			dst.DocumentWithAddressInformationReport = nil
		} else {
			if err = validator.Validate(dst.DocumentWithAddressInformationReport); err != nil {
				dst.DocumentWithAddressInformationReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentWithAddressInformationReport = nil
	}

	// try to unmarshal data into DocumentWithDriverVerificationReport
	err = newStrictDecoder(data).Decode(&dst.DocumentWithDriverVerificationReport)
	if err == nil {
		jsonDocumentWithDriverVerificationReport, _ := json.Marshal(dst.DocumentWithDriverVerificationReport)
		if string(jsonDocumentWithDriverVerificationReport) == "{}" { // empty struct
			dst.DocumentWithDriverVerificationReport = nil
		} else {
			if err = validator.Validate(dst.DocumentWithDriverVerificationReport); err != nil {
				dst.DocumentWithDriverVerificationReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentWithDriverVerificationReport = nil
	}

	// try to unmarshal data into DocumentWithDrivingLicenceInformationReport
	err = newStrictDecoder(data).Decode(&dst.DocumentWithDrivingLicenceInformationReport)
	if err == nil {
		jsonDocumentWithDrivingLicenceInformationReport, _ := json.Marshal(dst.DocumentWithDrivingLicenceInformationReport)
		if string(jsonDocumentWithDrivingLicenceInformationReport) == "{}" { // empty struct
			dst.DocumentWithDrivingLicenceInformationReport = nil
		} else {
			if err = validator.Validate(dst.DocumentWithDrivingLicenceInformationReport); err != nil {
				dst.DocumentWithDrivingLicenceInformationReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.DocumentWithDrivingLicenceInformationReport = nil
	}

	// try to unmarshal data into FacialSimilarityMotionReport
	err = newStrictDecoder(data).Decode(&dst.FacialSimilarityMotionReport)
	if err == nil {
		jsonFacialSimilarityMotionReport, _ := json.Marshal(dst.FacialSimilarityMotionReport)
		if string(jsonFacialSimilarityMotionReport) == "{}" { // empty struct
			dst.FacialSimilarityMotionReport = nil
		} else {
			if err = validator.Validate(dst.FacialSimilarityMotionReport); err != nil {
				dst.FacialSimilarityMotionReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.FacialSimilarityMotionReport = nil
	}

	// try to unmarshal data into FacialSimilarityPhotoFullyAutoReport
	err = newStrictDecoder(data).Decode(&dst.FacialSimilarityPhotoFullyAutoReport)
	if err == nil {
		jsonFacialSimilarityPhotoFullyAutoReport, _ := json.Marshal(dst.FacialSimilarityPhotoFullyAutoReport)
		if string(jsonFacialSimilarityPhotoFullyAutoReport) == "{}" { // empty struct
			dst.FacialSimilarityPhotoFullyAutoReport = nil
		} else {
			if err = validator.Validate(dst.FacialSimilarityPhotoFullyAutoReport); err != nil {
				dst.FacialSimilarityPhotoFullyAutoReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.FacialSimilarityPhotoFullyAutoReport = nil
	}

	// try to unmarshal data into FacialSimilarityPhotoReport
	err = newStrictDecoder(data).Decode(&dst.FacialSimilarityPhotoReport)
	if err == nil {
		jsonFacialSimilarityPhotoReport, _ := json.Marshal(dst.FacialSimilarityPhotoReport)
		if string(jsonFacialSimilarityPhotoReport) == "{}" { // empty struct
			dst.FacialSimilarityPhotoReport = nil
		} else {
			if err = validator.Validate(dst.FacialSimilarityPhotoReport); err != nil {
				dst.FacialSimilarityPhotoReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.FacialSimilarityPhotoReport = nil
	}

	// try to unmarshal data into FacialSimilarityVideoReport
	err = newStrictDecoder(data).Decode(&dst.FacialSimilarityVideoReport)
	if err == nil {
		jsonFacialSimilarityVideoReport, _ := json.Marshal(dst.FacialSimilarityVideoReport)
		if string(jsonFacialSimilarityVideoReport) == "{}" { // empty struct
			dst.FacialSimilarityVideoReport = nil
		} else {
			if err = validator.Validate(dst.FacialSimilarityVideoReport); err != nil {
				dst.FacialSimilarityVideoReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.FacialSimilarityVideoReport = nil
	}

	// try to unmarshal data into IdentityEnhancedReport
	err = newStrictDecoder(data).Decode(&dst.IdentityEnhancedReport)
	if err == nil {
		jsonIdentityEnhancedReport, _ := json.Marshal(dst.IdentityEnhancedReport)
		if string(jsonIdentityEnhancedReport) == "{}" { // empty struct
			dst.IdentityEnhancedReport = nil
		} else {
			if err = validator.Validate(dst.IdentityEnhancedReport); err != nil {
				dst.IdentityEnhancedReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.IdentityEnhancedReport = nil
	}

	// try to unmarshal data into IndiaPanReport
	err = newStrictDecoder(data).Decode(&dst.IndiaPanReport)
	if err == nil {
		jsonIndiaPanReport, _ := json.Marshal(dst.IndiaPanReport)
		if string(jsonIndiaPanReport) == "{}" { // empty struct
			dst.IndiaPanReport = nil
		} else {
			if err = validator.Validate(dst.IndiaPanReport); err != nil {
				dst.IndiaPanReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.IndiaPanReport = nil
	}

	// try to unmarshal data into KnownFacesReport
	err = newStrictDecoder(data).Decode(&dst.KnownFacesReport)
	if err == nil {
		jsonKnownFacesReport, _ := json.Marshal(dst.KnownFacesReport)
		if string(jsonKnownFacesReport) == "{}" { // empty struct
			dst.KnownFacesReport = nil
		} else {
			if err = validator.Validate(dst.KnownFacesReport); err != nil {
				dst.KnownFacesReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.KnownFacesReport = nil
	}

	// try to unmarshal data into ProofOfAddressReport
	err = newStrictDecoder(data).Decode(&dst.ProofOfAddressReport)
	if err == nil {
		jsonProofOfAddressReport, _ := json.Marshal(dst.ProofOfAddressReport)
		if string(jsonProofOfAddressReport) == "{}" { // empty struct
			dst.ProofOfAddressReport = nil
		} else {
			if err = validator.Validate(dst.ProofOfAddressReport); err != nil {
				dst.ProofOfAddressReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProofOfAddressReport = nil
	}

	// try to unmarshal data into UsDrivingLicenceReport
	err = newStrictDecoder(data).Decode(&dst.UsDrivingLicenceReport)
	if err == nil {
		jsonUsDrivingLicenceReport, _ := json.Marshal(dst.UsDrivingLicenceReport)
		if string(jsonUsDrivingLicenceReport) == "{}" { // empty struct
			dst.UsDrivingLicenceReport = nil
		} else {
			if err = validator.Validate(dst.UsDrivingLicenceReport); err != nil {
				dst.UsDrivingLicenceReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.UsDrivingLicenceReport = nil
	}

	// try to unmarshal data into WatchlistAmlReport
	err = newStrictDecoder(data).Decode(&dst.WatchlistAmlReport)
	if err == nil {
		jsonWatchlistAmlReport, _ := json.Marshal(dst.WatchlistAmlReport)
		if string(jsonWatchlistAmlReport) == "{}" { // empty struct
			dst.WatchlistAmlReport = nil
		} else {
			if err = validator.Validate(dst.WatchlistAmlReport); err != nil {
				dst.WatchlistAmlReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.WatchlistAmlReport = nil
	}

	// try to unmarshal data into WatchlistEnhancedReport
	err = newStrictDecoder(data).Decode(&dst.WatchlistEnhancedReport)
	if err == nil {
		jsonWatchlistEnhancedReport, _ := json.Marshal(dst.WatchlistEnhancedReport)
		if string(jsonWatchlistEnhancedReport) == "{}" { // empty struct
			dst.WatchlistEnhancedReport = nil
		} else {
			if err = validator.Validate(dst.WatchlistEnhancedReport); err != nil {
				dst.WatchlistEnhancedReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.WatchlistEnhancedReport = nil
	}

	// try to unmarshal data into WatchlistPepsOnlyReport
	err = newStrictDecoder(data).Decode(&dst.WatchlistPepsOnlyReport)
	if err == nil {
		jsonWatchlistPepsOnlyReport, _ := json.Marshal(dst.WatchlistPepsOnlyReport)
		if string(jsonWatchlistPepsOnlyReport) == "{}" { // empty struct
			dst.WatchlistPepsOnlyReport = nil
		} else {
			if err = validator.Validate(dst.WatchlistPepsOnlyReport); err != nil {
				dst.WatchlistPepsOnlyReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.WatchlistPepsOnlyReport = nil
	}

	// try to unmarshal data into WatchlistSanctionsOnlyReport
	err = newStrictDecoder(data).Decode(&dst.WatchlistSanctionsOnlyReport)
	if err == nil {
		jsonWatchlistSanctionsOnlyReport, _ := json.Marshal(dst.WatchlistSanctionsOnlyReport)
		if string(jsonWatchlistSanctionsOnlyReport) == "{}" { // empty struct
			dst.WatchlistSanctionsOnlyReport = nil
		} else {
			if err = validator.Validate(dst.WatchlistSanctionsOnlyReport); err != nil {
				dst.WatchlistSanctionsOnlyReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.WatchlistSanctionsOnlyReport = nil
	}

	// try to unmarshal data into WatchlistStandardReport
	err = newStrictDecoder(data).Decode(&dst.WatchlistStandardReport)
	if err == nil {
		jsonWatchlistStandardReport, _ := json.Marshal(dst.WatchlistStandardReport)
		if string(jsonWatchlistStandardReport) == "{}" { // empty struct
			dst.WatchlistStandardReport = nil
		} else {
			if err = validator.Validate(dst.WatchlistStandardReport); err != nil {
				dst.WatchlistStandardReport = nil
			} else {
				match++
			}
		}
	} else {
		dst.WatchlistStandardReport = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DeviceIntelligenceReport = nil
		dst.DocumentReport = nil
		dst.DocumentVideoReport = nil
		dst.DocumentVideoWithAddressInformationReport = nil
		dst.DocumentWithAddressInformationReport = nil
		dst.DocumentWithDriverVerificationReport = nil
		dst.DocumentWithDrivingLicenceInformationReport = nil
		dst.FacialSimilarityMotionReport = nil
		dst.FacialSimilarityPhotoFullyAutoReport = nil
		dst.FacialSimilarityPhotoReport = nil
		dst.FacialSimilarityVideoReport = nil
		dst.IdentityEnhancedReport = nil
		dst.IndiaPanReport = nil
		dst.KnownFacesReport = nil
		dst.ProofOfAddressReport = nil
		dst.UsDrivingLicenceReport = nil
		dst.WatchlistAmlReport = nil
		dst.WatchlistEnhancedReport = nil
		dst.WatchlistPepsOnlyReport = nil
		dst.WatchlistSanctionsOnlyReport = nil
		dst.WatchlistStandardReport = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Report)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Report)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Report) MarshalJSON() ([]byte, error) {
	if src.DeviceIntelligenceReport != nil {
		return json.Marshal(&src.DeviceIntelligenceReport)
	}

	if src.DocumentReport != nil {
		return json.Marshal(&src.DocumentReport)
	}

	if src.DocumentVideoReport != nil {
		return json.Marshal(&src.DocumentVideoReport)
	}

	if src.DocumentVideoWithAddressInformationReport != nil {
		return json.Marshal(&src.DocumentVideoWithAddressInformationReport)
	}

	if src.DocumentWithAddressInformationReport != nil {
		return json.Marshal(&src.DocumentWithAddressInformationReport)
	}

	if src.DocumentWithDriverVerificationReport != nil {
		return json.Marshal(&src.DocumentWithDriverVerificationReport)
	}

	if src.DocumentWithDrivingLicenceInformationReport != nil {
		return json.Marshal(&src.DocumentWithDrivingLicenceInformationReport)
	}

	if src.FacialSimilarityMotionReport != nil {
		return json.Marshal(&src.FacialSimilarityMotionReport)
	}

	if src.FacialSimilarityPhotoFullyAutoReport != nil {
		return json.Marshal(&src.FacialSimilarityPhotoFullyAutoReport)
	}

	if src.FacialSimilarityPhotoReport != nil {
		return json.Marshal(&src.FacialSimilarityPhotoReport)
	}

	if src.FacialSimilarityVideoReport != nil {
		return json.Marshal(&src.FacialSimilarityVideoReport)
	}

	if src.IdentityEnhancedReport != nil {
		return json.Marshal(&src.IdentityEnhancedReport)
	}

	if src.IndiaPanReport != nil {
		return json.Marshal(&src.IndiaPanReport)
	}

	if src.KnownFacesReport != nil {
		return json.Marshal(&src.KnownFacesReport)
	}

	if src.ProofOfAddressReport != nil {
		return json.Marshal(&src.ProofOfAddressReport)
	}

	if src.UsDrivingLicenceReport != nil {
		return json.Marshal(&src.UsDrivingLicenceReport)
	}

	if src.WatchlistAmlReport != nil {
		return json.Marshal(&src.WatchlistAmlReport)
	}

	if src.WatchlistEnhancedReport != nil {
		return json.Marshal(&src.WatchlistEnhancedReport)
	}

	if src.WatchlistPepsOnlyReport != nil {
		return json.Marshal(&src.WatchlistPepsOnlyReport)
	}

	if src.WatchlistSanctionsOnlyReport != nil {
		return json.Marshal(&src.WatchlistSanctionsOnlyReport)
	}

	if src.WatchlistStandardReport != nil {
		return json.Marshal(&src.WatchlistStandardReport)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Report) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DeviceIntelligenceReport != nil {
		return obj.DeviceIntelligenceReport
	}

	if obj.DocumentReport != nil {
		return obj.DocumentReport
	}

	if obj.DocumentVideoReport != nil {
		return obj.DocumentVideoReport
	}

	if obj.DocumentVideoWithAddressInformationReport != nil {
		return obj.DocumentVideoWithAddressInformationReport
	}

	if obj.DocumentWithAddressInformationReport != nil {
		return obj.DocumentWithAddressInformationReport
	}

	if obj.DocumentWithDriverVerificationReport != nil {
		return obj.DocumentWithDriverVerificationReport
	}

	if obj.DocumentWithDrivingLicenceInformationReport != nil {
		return obj.DocumentWithDrivingLicenceInformationReport
	}

	if obj.FacialSimilarityMotionReport != nil {
		return obj.FacialSimilarityMotionReport
	}

	if obj.FacialSimilarityPhotoFullyAutoReport != nil {
		return obj.FacialSimilarityPhotoFullyAutoReport
	}

	if obj.FacialSimilarityPhotoReport != nil {
		return obj.FacialSimilarityPhotoReport
	}

	if obj.FacialSimilarityVideoReport != nil {
		return obj.FacialSimilarityVideoReport
	}

	if obj.IdentityEnhancedReport != nil {
		return obj.IdentityEnhancedReport
	}

	if obj.IndiaPanReport != nil {
		return obj.IndiaPanReport
	}

	if obj.KnownFacesReport != nil {
		return obj.KnownFacesReport
	}

	if obj.ProofOfAddressReport != nil {
		return obj.ProofOfAddressReport
	}

	if obj.UsDrivingLicenceReport != nil {
		return obj.UsDrivingLicenceReport
	}

	if obj.WatchlistAmlReport != nil {
		return obj.WatchlistAmlReport
	}

	if obj.WatchlistEnhancedReport != nil {
		return obj.WatchlistEnhancedReport
	}

	if obj.WatchlistPepsOnlyReport != nil {
		return obj.WatchlistPepsOnlyReport
	}

	if obj.WatchlistSanctionsOnlyReport != nil {
		return obj.WatchlistSanctionsOnlyReport
	}

	if obj.WatchlistStandardReport != nil {
		return obj.WatchlistStandardReport
	}

	// all schemas are nil
	return nil
}

type NullableReport struct {
	value *Report
	isSet bool
}

func (v NullableReport) Get() *Report {
	return v.value
}

func (v *NullableReport) Set(val *Report) {
	v.value = val
	v.isSet = true
}

func (v NullableReport) IsSet() bool {
	return v.isSet
}

func (v *NullableReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReport(val *Report) *NullableReport {
	return &NullableReport{value: val, isSet: true}
}

func (v NullableReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


