/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckRequest{}

// CheckRequest struct for CheckRequest
type CheckRequest struct {
	// An array of report names (strings).
	ReportNames []ReportName `json:"report_names"`
	// Optional. An array of document ids, for use with Document reports only. If omitted, the Document report will use the most recently uploaded document by default.
	DocumentIds []string `json:"document_ids,omitempty"`
	// Send an applicant form to applicant to complete to proceed with check. Defaults to false.
	ApplicantProvidesData *bool `json:"applicant_provides_data,omitempty"`
	// Defaults to `true`. If set to `false`, you will only receive a response when all reports in your check have completed. 
	Asynchronous *bool `json:"asynchronous,omitempty"`
	// For checks where `applicant_provides_data` is `true`, applicant form will not be automatically sent if `suppress_form_emails` is set to `true`. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Write-only. Defaults to false. 
	SuppressFormEmails *bool `json:"suppress_form_emails,omitempty"`
	// Triggers responses for particular sub-results for sandbox Document reports.
	SubResult *string `json:"sub_result,omitempty"`
	// Array of names of particular reports to return consider as their results. This is a feature available in sandbox testing
	Consider []ReportName `json:"consider,omitempty"`
	UsDrivingLicence *UsDrivingLicenceBuilder `json:"us_driving_licence,omitempty"`
}

type _CheckRequest CheckRequest

// NewCheckRequest instantiates a new CheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckRequest(reportNames []ReportName) *CheckRequest {
	this := CheckRequest{}
	this.ReportNames = reportNames
	var applicantProvidesData bool = false
	this.ApplicantProvidesData = &applicantProvidesData
	var asynchronous bool = true
	this.Asynchronous = &asynchronous
	return &this
}

// NewCheckRequestWithDefaults instantiates a new CheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckRequestWithDefaults() *CheckRequest {
	this := CheckRequest{}
	var applicantProvidesData bool = false
	this.ApplicantProvidesData = &applicantProvidesData
	var asynchronous bool = true
	this.Asynchronous = &asynchronous
	return &this
}

// GetReportNames returns the ReportNames field value
func (o *CheckRequest) GetReportNames() []ReportName {
	if o == nil {
		var ret []ReportName
		return ret
	}

	return o.ReportNames
}

// GetReportNamesOk returns a tuple with the ReportNames field value
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetReportNamesOk() ([]ReportName, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReportNames, true
}

// SetReportNames sets field value
func (o *CheckRequest) SetReportNames(v []ReportName) {
	o.ReportNames = v
}

// GetDocumentIds returns the DocumentIds field value if set, zero value otherwise.
func (o *CheckRequest) GetDocumentIds() []string {
	if o == nil || IsNil(o.DocumentIds) {
		var ret []string
		return ret
	}
	return o.DocumentIds
}

// GetDocumentIdsOk returns a tuple with the DocumentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetDocumentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DocumentIds) {
		return nil, false
	}
	return o.DocumentIds, true
}

// HasDocumentIds returns a boolean if a field has been set.
func (o *CheckRequest) HasDocumentIds() bool {
	if o != nil && !IsNil(o.DocumentIds) {
		return true
	}

	return false
}

// SetDocumentIds gets a reference to the given []string and assigns it to the DocumentIds field.
func (o *CheckRequest) SetDocumentIds(v []string) {
	o.DocumentIds = v
}

// GetApplicantProvidesData returns the ApplicantProvidesData field value if set, zero value otherwise.
func (o *CheckRequest) GetApplicantProvidesData() bool {
	if o == nil || IsNil(o.ApplicantProvidesData) {
		var ret bool
		return ret
	}
	return *o.ApplicantProvidesData
}

// GetApplicantProvidesDataOk returns a tuple with the ApplicantProvidesData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetApplicantProvidesDataOk() (*bool, bool) {
	if o == nil || IsNil(o.ApplicantProvidesData) {
		return nil, false
	}
	return o.ApplicantProvidesData, true
}

// HasApplicantProvidesData returns a boolean if a field has been set.
func (o *CheckRequest) HasApplicantProvidesData() bool {
	if o != nil && !IsNil(o.ApplicantProvidesData) {
		return true
	}

	return false
}

// SetApplicantProvidesData gets a reference to the given bool and assigns it to the ApplicantProvidesData field.
func (o *CheckRequest) SetApplicantProvidesData(v bool) {
	o.ApplicantProvidesData = &v
}

// GetAsynchronous returns the Asynchronous field value if set, zero value otherwise.
func (o *CheckRequest) GetAsynchronous() bool {
	if o == nil || IsNil(o.Asynchronous) {
		var ret bool
		return ret
	}
	return *o.Asynchronous
}

// GetAsynchronousOk returns a tuple with the Asynchronous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetAsynchronousOk() (*bool, bool) {
	if o == nil || IsNil(o.Asynchronous) {
		return nil, false
	}
	return o.Asynchronous, true
}

// HasAsynchronous returns a boolean if a field has been set.
func (o *CheckRequest) HasAsynchronous() bool {
	if o != nil && !IsNil(o.Asynchronous) {
		return true
	}

	return false
}

// SetAsynchronous gets a reference to the given bool and assigns it to the Asynchronous field.
func (o *CheckRequest) SetAsynchronous(v bool) {
	o.Asynchronous = &v
}

// GetSuppressFormEmails returns the SuppressFormEmails field value if set, zero value otherwise.
func (o *CheckRequest) GetSuppressFormEmails() bool {
	if o == nil || IsNil(o.SuppressFormEmails) {
		var ret bool
		return ret
	}
	return *o.SuppressFormEmails
}

// GetSuppressFormEmailsOk returns a tuple with the SuppressFormEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetSuppressFormEmailsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuppressFormEmails) {
		return nil, false
	}
	return o.SuppressFormEmails, true
}

// HasSuppressFormEmails returns a boolean if a field has been set.
func (o *CheckRequest) HasSuppressFormEmails() bool {
	if o != nil && !IsNil(o.SuppressFormEmails) {
		return true
	}

	return false
}

// SetSuppressFormEmails gets a reference to the given bool and assigns it to the SuppressFormEmails field.
func (o *CheckRequest) SetSuppressFormEmails(v bool) {
	o.SuppressFormEmails = &v
}

// GetSubResult returns the SubResult field value if set, zero value otherwise.
func (o *CheckRequest) GetSubResult() string {
	if o == nil || IsNil(o.SubResult) {
		var ret string
		return ret
	}
	return *o.SubResult
}

// GetSubResultOk returns a tuple with the SubResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetSubResultOk() (*string, bool) {
	if o == nil || IsNil(o.SubResult) {
		return nil, false
	}
	return o.SubResult, true
}

// HasSubResult returns a boolean if a field has been set.
func (o *CheckRequest) HasSubResult() bool {
	if o != nil && !IsNil(o.SubResult) {
		return true
	}

	return false
}

// SetSubResult gets a reference to the given string and assigns it to the SubResult field.
func (o *CheckRequest) SetSubResult(v string) {
	o.SubResult = &v
}

// GetConsider returns the Consider field value if set, zero value otherwise.
func (o *CheckRequest) GetConsider() []ReportName {
	if o == nil || IsNil(o.Consider) {
		var ret []ReportName
		return ret
	}
	return o.Consider
}

// GetConsiderOk returns a tuple with the Consider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetConsiderOk() ([]ReportName, bool) {
	if o == nil || IsNil(o.Consider) {
		return nil, false
	}
	return o.Consider, true
}

// HasConsider returns a boolean if a field has been set.
func (o *CheckRequest) HasConsider() bool {
	if o != nil && !IsNil(o.Consider) {
		return true
	}

	return false
}

// SetConsider gets a reference to the given []ReportName and assigns it to the Consider field.
func (o *CheckRequest) SetConsider(v []ReportName) {
	o.Consider = v
}

// GetUsDrivingLicence returns the UsDrivingLicence field value if set, zero value otherwise.
func (o *CheckRequest) GetUsDrivingLicence() UsDrivingLicenceBuilder {
	if o == nil || IsNil(o.UsDrivingLicence) {
		var ret UsDrivingLicenceBuilder
		return ret
	}
	return *o.UsDrivingLicence
}

// GetUsDrivingLicenceOk returns a tuple with the UsDrivingLicence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckRequest) GetUsDrivingLicenceOk() (*UsDrivingLicenceBuilder, bool) {
	if o == nil || IsNil(o.UsDrivingLicence) {
		return nil, false
	}
	return o.UsDrivingLicence, true
}

// HasUsDrivingLicence returns a boolean if a field has been set.
func (o *CheckRequest) HasUsDrivingLicence() bool {
	if o != nil && !IsNil(o.UsDrivingLicence) {
		return true
	}

	return false
}

// SetUsDrivingLicence gets a reference to the given UsDrivingLicenceBuilder and assigns it to the UsDrivingLicence field.
func (o *CheckRequest) SetUsDrivingLicence(v UsDrivingLicenceBuilder) {
	o.UsDrivingLicence = &v
}

func (o CheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["report_names"] = o.ReportNames
	if !IsNil(o.DocumentIds) {
		toSerialize["document_ids"] = o.DocumentIds
	}
	if !IsNil(o.ApplicantProvidesData) {
		toSerialize["applicant_provides_data"] = o.ApplicantProvidesData
	}
	if !IsNil(o.Asynchronous) {
		toSerialize["asynchronous"] = o.Asynchronous
	}
	if !IsNil(o.SuppressFormEmails) {
		toSerialize["suppress_form_emails"] = o.SuppressFormEmails
	}
	if !IsNil(o.SubResult) {
		toSerialize["sub_result"] = o.SubResult
	}
	if !IsNil(o.Consider) {
		toSerialize["consider"] = o.Consider
	}
	if !IsNil(o.UsDrivingLicence) {
		toSerialize["us_driving_licence"] = o.UsDrivingLicence
	}
	return toSerialize, nil
}

func (o *CheckRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"report_names",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckRequest := _CheckRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckRequest)

	if err != nil {
		return err
	}

	*o = CheckRequest(varCheckRequest)

	return err
}

type NullableCheckRequest struct {
	value *CheckRequest
	isSet bool
}

func (v NullableCheckRequest) Get() *CheckRequest {
	return v.value
}

func (v *NullableCheckRequest) Set(val *CheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckRequest(val *CheckRequest) *NullableCheckRequest {
	return &NullableCheckRequest{value: val, isSet: true}
}

func (v NullableCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


