/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookBuilder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookBuilder{}

// WebhookBuilder struct for WebhookBuilder
type WebhookBuilder struct {
	// Determine if the webhook is active.
	Enabled *bool `json:"enabled,omitempty"`
	// The events that will be published to the webhook. If the events parameter is omitted all the events will be subscribed. 
	Events []WebhookEventType `json:"events,omitempty"`
	// The environments from which the webhook will receive events. Allowed values are “sandbox” and “live”. If the environments parameter is omitted the webhook will receive events from both environments. 
	Environments []string `json:"environments,omitempty"`
	// Webhook version used to control the payload object when sending webhooks.
	PayloadVersion *int32 `json:"payload_version,omitempty"`
	// The url that will listen to notifications (must be https).
	Url string `json:"url"`
}

type _WebhookBuilder WebhookBuilder

// NewWebhookBuilder instantiates a new WebhookBuilder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookBuilder(url string) *WebhookBuilder {
	this := WebhookBuilder{}
	this.Url = url
	return &this
}

// NewWebhookBuilderWithDefaults instantiates a new WebhookBuilder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookBuilderWithDefaults() *WebhookBuilder {
	this := WebhookBuilder{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *WebhookBuilder) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookBuilder) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *WebhookBuilder) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *WebhookBuilder) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *WebhookBuilder) GetEvents() []WebhookEventType {
	if o == nil || IsNil(o.Events) {
		var ret []WebhookEventType
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookBuilder) GetEventsOk() ([]WebhookEventType, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookBuilder) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []WebhookEventType and assigns it to the Events field.
func (o *WebhookBuilder) SetEvents(v []WebhookEventType) {
	o.Events = v
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *WebhookBuilder) GetEnvironments() []string {
	if o == nil || IsNil(o.Environments) {
		var ret []string
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookBuilder) GetEnvironmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *WebhookBuilder) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []string and assigns it to the Environments field.
func (o *WebhookBuilder) SetEnvironments(v []string) {
	o.Environments = v
}

// GetPayloadVersion returns the PayloadVersion field value if set, zero value otherwise.
func (o *WebhookBuilder) GetPayloadVersion() int32 {
	if o == nil || IsNil(o.PayloadVersion) {
		var ret int32
		return ret
	}
	return *o.PayloadVersion
}

// GetPayloadVersionOk returns a tuple with the PayloadVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookBuilder) GetPayloadVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.PayloadVersion) {
		return nil, false
	}
	return o.PayloadVersion, true
}

// HasPayloadVersion returns a boolean if a field has been set.
func (o *WebhookBuilder) HasPayloadVersion() bool {
	if o != nil && !IsNil(o.PayloadVersion) {
		return true
	}

	return false
}

// SetPayloadVersion gets a reference to the given int32 and assigns it to the PayloadVersion field.
func (o *WebhookBuilder) SetPayloadVersion(v int32) {
	o.PayloadVersion = &v
}

// GetUrl returns the Url field value
func (o *WebhookBuilder) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookBuilder) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookBuilder) SetUrl(v string) {
	o.Url = v
}

func (o WebhookBuilder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookBuilder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	if !IsNil(o.PayloadVersion) {
		toSerialize["payload_version"] = o.PayloadVersion
	}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *WebhookBuilder) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookBuilder := _WebhookBuilder{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookBuilder)

	if err != nil {
		return err
	}

	*o = WebhookBuilder(varWebhookBuilder)

	return err
}

type NullableWebhookBuilder struct {
	value *WebhookBuilder
	isSet bool
}

func (v NullableWebhookBuilder) Get() *WebhookBuilder {
	return v.value
}

func (v *NullableWebhookBuilder) Set(val *WebhookBuilder) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookBuilder) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookBuilder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookBuilder(val *WebhookBuilder) *NullableWebhookBuilder {
	return &NullableWebhookBuilder{value: val, isSet: true}
}

func (v NullableWebhookBuilder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookBuilder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


