/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WatchlistAmlBreakdownAdverseMedia type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchlistAmlBreakdownAdverseMedia{}

// WatchlistAmlBreakdownAdverseMedia Asserts if there are any records found of negative events reported by publicly and generally available media sources.
type WatchlistAmlBreakdownAdverseMedia struct {
	Result *string `json:"result,omitempty"`
}

// NewWatchlistAmlBreakdownAdverseMedia instantiates a new WatchlistAmlBreakdownAdverseMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchlistAmlBreakdownAdverseMedia() *WatchlistAmlBreakdownAdverseMedia {
	this := WatchlistAmlBreakdownAdverseMedia{}
	return &this
}

// NewWatchlistAmlBreakdownAdverseMediaWithDefaults instantiates a new WatchlistAmlBreakdownAdverseMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchlistAmlBreakdownAdverseMediaWithDefaults() *WatchlistAmlBreakdownAdverseMedia {
	this := WatchlistAmlBreakdownAdverseMedia{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *WatchlistAmlBreakdownAdverseMedia) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistAmlBreakdownAdverseMedia) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *WatchlistAmlBreakdownAdverseMedia) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *WatchlistAmlBreakdownAdverseMedia) SetResult(v string) {
	o.Result = &v
}

func (o WatchlistAmlBreakdownAdverseMedia) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchlistAmlBreakdownAdverseMedia) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableWatchlistAmlBreakdownAdverseMedia struct {
	value *WatchlistAmlBreakdownAdverseMedia
	isSet bool
}

func (v NullableWatchlistAmlBreakdownAdverseMedia) Get() *WatchlistAmlBreakdownAdverseMedia {
	return v.value
}

func (v *NullableWatchlistAmlBreakdownAdverseMedia) Set(val *WatchlistAmlBreakdownAdverseMedia) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchlistAmlBreakdownAdverseMedia) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchlistAmlBreakdownAdverseMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchlistAmlBreakdownAdverseMedia(val *WatchlistAmlBreakdownAdverseMedia) *NullableWatchlistAmlBreakdownAdverseMedia {
	return &NullableWatchlistAmlBreakdownAdverseMedia{value: val, isSet: true}
}

func (v NullableWatchlistAmlBreakdownAdverseMedia) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchlistAmlBreakdownAdverseMedia) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


