/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WorkflowRunRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowRunRequest{}

// WorkflowRunRequest struct for WorkflowRunRequest
type WorkflowRunRequest struct {
	// Object with Custom Input Data to be used in the Workflow Run.
	CustomData map[string]interface{} `json:"custom_data,omitempty"`
}

// NewWorkflowRunRequest instantiates a new WorkflowRunRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunRequest() *WorkflowRunRequest {
	this := WorkflowRunRequest{}
	return &this
}

// NewWorkflowRunRequestWithDefaults instantiates a new WorkflowRunRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunRequestWithDefaults() *WorkflowRunRequest {
	this := WorkflowRunRequest{}
	return &this
}

// GetCustomData returns the CustomData field value if set, zero value otherwise.
func (o *WorkflowRunRequest) GetCustomData() map[string]interface{} {
	if o == nil || IsNil(o.CustomData) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomData
}

// GetCustomDataOk returns a tuple with the CustomData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunRequest) GetCustomDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomData) {
		return map[string]interface{}{}, false
	}
	return o.CustomData, true
}

// HasCustomData returns a boolean if a field has been set.
func (o *WorkflowRunRequest) HasCustomData() bool {
	if o != nil && !IsNil(o.CustomData) {
		return true
	}

	return false
}

// SetCustomData gets a reference to the given map[string]interface{} and assigns it to the CustomData field.
func (o *WorkflowRunRequest) SetCustomData(v map[string]interface{}) {
	o.CustomData = v
}

func (o WorkflowRunRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowRunRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomData) {
		toSerialize["custom_data"] = o.CustomData
	}
	return toSerialize, nil
}

type NullableWorkflowRunRequest struct {
	value *WorkflowRunRequest
	isSet bool
}

func (v NullableWorkflowRunRequest) Get() *WorkflowRunRequest {
	return v.value
}

func (v *NullableWorkflowRunRequest) Set(val *WorkflowRunRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunRequest(val *WorkflowRunRequest) *NullableWorkflowRunRequest {
	return &NullableWorkflowRunRequest{value: val, isSet: true}
}

func (v NullableWorkflowRunRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


