/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityMotionBreakdownFaceComparison type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityMotionBreakdownFaceComparison{}

// FacialSimilarityMotionBreakdownFaceComparison Asserts whether the face in the document matches the face in the motion capture.
type FacialSimilarityMotionBreakdownFaceComparison struct {
	Result *string `json:"result,omitempty"`
	Breakdown *FacialSimilarityPhotoBreakdownFaceComparisonBreakdown `json:"breakdown,omitempty"`
}

// NewFacialSimilarityMotionBreakdownFaceComparison instantiates a new FacialSimilarityMotionBreakdownFaceComparison object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityMotionBreakdownFaceComparison() *FacialSimilarityMotionBreakdownFaceComparison {
	this := FacialSimilarityMotionBreakdownFaceComparison{}
	return &this
}

// NewFacialSimilarityMotionBreakdownFaceComparisonWithDefaults instantiates a new FacialSimilarityMotionBreakdownFaceComparison object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityMotionBreakdownFaceComparisonWithDefaults() *FacialSimilarityMotionBreakdownFaceComparison {
	this := FacialSimilarityMotionBreakdownFaceComparison{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FacialSimilarityMotionBreakdownFaceComparison) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityMotionBreakdownFaceComparison) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FacialSimilarityMotionBreakdownFaceComparison) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *FacialSimilarityMotionBreakdownFaceComparison) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *FacialSimilarityMotionBreakdownFaceComparison) GetBreakdown() FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret FacialSimilarityPhotoBreakdownFaceComparisonBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityMotionBreakdownFaceComparison) GetBreakdownOk() (*FacialSimilarityPhotoBreakdownFaceComparisonBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *FacialSimilarityMotionBreakdownFaceComparison) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given FacialSimilarityPhotoBreakdownFaceComparisonBreakdown and assigns it to the Breakdown field.
func (o *FacialSimilarityMotionBreakdownFaceComparison) SetBreakdown(v FacialSimilarityPhotoBreakdownFaceComparisonBreakdown) {
	o.Breakdown = &v
}

func (o FacialSimilarityMotionBreakdownFaceComparison) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityMotionBreakdownFaceComparison) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableFacialSimilarityMotionBreakdownFaceComparison struct {
	value *FacialSimilarityMotionBreakdownFaceComparison
	isSet bool
}

func (v NullableFacialSimilarityMotionBreakdownFaceComparison) Get() *FacialSimilarityMotionBreakdownFaceComparison {
	return v.value
}

func (v *NullableFacialSimilarityMotionBreakdownFaceComparison) Set(val *FacialSimilarityMotionBreakdownFaceComparison) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityMotionBreakdownFaceComparison) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityMotionBreakdownFaceComparison) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityMotionBreakdownFaceComparison(val *FacialSimilarityMotionBreakdownFaceComparison) *NullableFacialSimilarityMotionBreakdownFaceComparison {
	return &NullableFacialSimilarityMotionBreakdownFaceComparison{value: val, isSet: true}
}

func (v NullableFacialSimilarityMotionBreakdownFaceComparison) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityMotionBreakdownFaceComparison) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


