/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WatchlistAmlBreakdownPoliticallyExposedPerson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchlistAmlBreakdownPoliticallyExposedPerson{}

// WatchlistAmlBreakdownPoliticallyExposedPerson Asserts if there are any records found in the proprietary database of Politically Exposed Persons sourced from government lists, websites and other media sources.
type WatchlistAmlBreakdownPoliticallyExposedPerson struct {
	Result *string `json:"result,omitempty"`
}

// NewWatchlistAmlBreakdownPoliticallyExposedPerson instantiates a new WatchlistAmlBreakdownPoliticallyExposedPerson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchlistAmlBreakdownPoliticallyExposedPerson() *WatchlistAmlBreakdownPoliticallyExposedPerson {
	this := WatchlistAmlBreakdownPoliticallyExposedPerson{}
	return &this
}

// NewWatchlistAmlBreakdownPoliticallyExposedPersonWithDefaults instantiates a new WatchlistAmlBreakdownPoliticallyExposedPerson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchlistAmlBreakdownPoliticallyExposedPersonWithDefaults() *WatchlistAmlBreakdownPoliticallyExposedPerson {
	this := WatchlistAmlBreakdownPoliticallyExposedPerson{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *WatchlistAmlBreakdownPoliticallyExposedPerson) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistAmlBreakdownPoliticallyExposedPerson) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *WatchlistAmlBreakdownPoliticallyExposedPerson) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *WatchlistAmlBreakdownPoliticallyExposedPerson) SetResult(v string) {
	o.Result = &v
}

func (o WatchlistAmlBreakdownPoliticallyExposedPerson) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchlistAmlBreakdownPoliticallyExposedPerson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableWatchlistAmlBreakdownPoliticallyExposedPerson struct {
	value *WatchlistAmlBreakdownPoliticallyExposedPerson
	isSet bool
}

func (v NullableWatchlistAmlBreakdownPoliticallyExposedPerson) Get() *WatchlistAmlBreakdownPoliticallyExposedPerson {
	return v.value
}

func (v *NullableWatchlistAmlBreakdownPoliticallyExposedPerson) Set(val *WatchlistAmlBreakdownPoliticallyExposedPerson) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchlistAmlBreakdownPoliticallyExposedPerson) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchlistAmlBreakdownPoliticallyExposedPerson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchlistAmlBreakdownPoliticallyExposedPerson(val *WatchlistAmlBreakdownPoliticallyExposedPerson) *NullableWatchlistAmlBreakdownPoliticallyExposedPerson {
	return &NullableWatchlistAmlBreakdownPoliticallyExposedPerson{value: val, isSet: true}
}

func (v NullableWatchlistAmlBreakdownPoliticallyExposedPerson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchlistAmlBreakdownPoliticallyExposedPerson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


