/*
Onfido API v3.6

The Onfido API (v3.6)

API version: v3.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the WatchlistAmlBreakdownLegalAndRegulatoryWarnings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchlistAmlBreakdownLegalAndRegulatoryWarnings{}

// WatchlistAmlBreakdownLegalAndRegulatoryWarnings Asserts if there are any records found in Law-Enforcement and Regulatory bodies Monitored Lists (including Terrorism, Money Laundering and Most Wanted lists).
type WatchlistAmlBreakdownLegalAndRegulatoryWarnings struct {
	Result *string `json:"result,omitempty"`
}

// NewWatchlistAmlBreakdownLegalAndRegulatoryWarnings instantiates a new WatchlistAmlBreakdownLegalAndRegulatoryWarnings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchlistAmlBreakdownLegalAndRegulatoryWarnings() *WatchlistAmlBreakdownLegalAndRegulatoryWarnings {
	this := WatchlistAmlBreakdownLegalAndRegulatoryWarnings{}
	return &this
}

// NewWatchlistAmlBreakdownLegalAndRegulatoryWarningsWithDefaults instantiates a new WatchlistAmlBreakdownLegalAndRegulatoryWarnings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchlistAmlBreakdownLegalAndRegulatoryWarningsWithDefaults() *WatchlistAmlBreakdownLegalAndRegulatoryWarnings {
	this := WatchlistAmlBreakdownLegalAndRegulatoryWarnings{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) SetResult(v string) {
	o.Result = &v
}

func (o WatchlistAmlBreakdownLegalAndRegulatoryWarnings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchlistAmlBreakdownLegalAndRegulatoryWarnings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings struct {
	value *WatchlistAmlBreakdownLegalAndRegulatoryWarnings
	isSet bool
}

func (v NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) Get() *WatchlistAmlBreakdownLegalAndRegulatoryWarnings {
	return v.value
}

func (v *NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) Set(val *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings(val *WatchlistAmlBreakdownLegalAndRegulatoryWarnings) *NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings {
	return &NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings{value: val, isSet: true}
}

func (v NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchlistAmlBreakdownLegalAndRegulatoryWarnings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


